file changes

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -52,7 +52,7 @@ jobs:
             if [ ! -d "venv" ]; then
                 echo "Creating virtual environment..."
                 # First, make sure python3-venv is installed
-                sudo apt-get install -y python3.10-venv || { echo "Failed to install python3.10-venv"; exit 1; }
+                sudo apt-get install -y python3-venv || { echo "Failed to install python3.10-venv"; exit 1; }
                 python3 -m venv venv || { echo "Failed to create virtual environment"; exit 1; }
             fi
           
